import dtlpy as dl
import os

path = '/home/noam/data'

dl.login_token(
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6Ik5qZERNMFV3TVRJMlJUVTVPVGcwTVRnd01ESTVRelpHTUVJek0wSkdORVl6TXpJek1qYzVRUSJ9.eyJodHRwczovL2RhdGFsb29wLmFpL2F1dGhvcml6YXRpb24iOnsiZ3JvdXBzIjpbInBpcGVyIl0sInJvbGVzIjpbXSwicGVybWlzc2lvbnMiOltdfSwiZW1haWwiOiJub2FtckBkYXRhbG9vcC5haSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczovL2RhdGFsb29wLWRldmVsb3BtZW50LmF1dGgwLmNvbS8iLCJzdWIiOiJnb29nbGUtb2F1dGgyfDExNDM1NDY2OTA1OTk5MDc3ODQxNiIsImF1ZCI6Ikk0QXJyOWl4czVSVDRxSWpPR3RJWjMwTVZYekVNNHc4IiwiaWF0IjoxNTc4MjEzNTM1LCJleHAiOjE1NzgyNzgzMzV9.F4ETp6VqhW2WokJhfcdh85eCNcbmOOHR7moai5iL_-ScWqCDjzg6ZL7_qK2sH8akgDIGVP9UkCM6dFotWuI3M7-pggsy9pd0Uo1H5uprUzsQhELpsU7UbF504VRXAQX1pVmpEDGFqs-TG9gvWX7T8KsbyP8PVN2M2aj7V5rwGtGqQoWSVYMpVkT7C_f9BzxQvH2txyzkBnQs-uaGmCX91qRingcps_f6AqN5xeWo7BUm8X51oHguUWw8MMjiGma48Xv2nmdeIPM9BeOeb5MlkJk9Iz35Gq_Sk1wWwImynw3zn6ps238Eawhgi93akdJZ7qTYVHPaKya_dYCLMflhoQ')
dl.setenv('dev')
project = dl.projects.get(project_id='buffs_project')
dataset_obj = project.datasets.get('my_data')
# dataset_obj.items.upload(local_path='/Users/noam/tiny_coco', remote_path='')
dataset_obj.items.download(local_path=path)
os.rename(os.path.join(path, 'items', 'tiny_coco'), os.path.join(path, 'tiny_coco'))