model:
  type: resnet50
dataset: cifar10
aug: fa_reduced_cifar10
cutout: 0
batch: 128
epoch: 270
lr: 0.05
lr_schedule:
  type: 'resnet'
  warmup:
    multiplier: 1
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0001
  clip: 0
  ema: 0
dataroot: '/home/noam/data/private/pretrainedmodels'
until: 5
"num_op": 2
"num-policy": 5
"num-search": 200
"cv-ratio": 0.4
"decay": -1

